name: Build SDL2 Image Libraries (Android)

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
    steps:

    - uses: actions/checkout@v4.1.7
      with:
        repository: 'libsdl-org/SDL_image'
        path: 'SDLImage'
        ref: 'release-2.8.2'
        submodules: true
    
    - uses: actions/checkout@v4.1.7
      with:
        repository: 'libsdl-org/SDL'
        ref: 'release-2.30.6'
        path: 'SDLImage/SDL2'

    - name: Install dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Install Android SDK Command-Line Tools
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O android-sdk-tools.zip
        unzip android-sdk-tools.zip -d tools
        mkdir $HOME/android-sdk/
        mkdir $HOME/android-sdk/cmdline-tools/
        mkdir $HOME/android-sdk/cmdline-tools/latest/
        mv ./tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
        chmod +x $HOME/android-sdk/cmdline-tools/latest/bin/*
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        
    - name: Accept Android SDK Licenses
      run: |
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses


    - name: Install Specific Android NDK Version 26.3.11579264
      run: |
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --install "ndk;26.3.11579264"      
        echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/26.3.11579264" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_HOME/ndk/26.3.11579264" >> $GITHUB_ENV

    - name: Build for arm64-v8a
      run: |
          cd SDLImage/SDL2
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_SYSTEM_NAME=Android \
                -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME \
                -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
                -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang \
                -DCMAKE_ANDROID_STL_TYPE=c++_shared \
                -DCMAKE_ANDROID_API=21 \
                -DANDROID_NDK=$ANDROID_NDK_HOME \
                -DSDL_STATIC=ON \
                -DSDL_SHARED=ON \
                -S ./ \
                -B ./build/arm64-v8a
          cmake --build ./build/arm64-v8a  --config Release

    - name: Build for x86_64
      run: |
          cd SDLImage/SDL2
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_SYSTEM_NAME=Android \
                -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME \
                -DCMAKE_ANDROID_ARCH_ABI=x86_64 \
                -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang \
                -DCMAKE_ANDROID_STL_TYPE=c++_shared \
                -DCMAKE_ANDROID_API=21 \
                -DANDROID_NDK=$ANDROID_NDK_HOME \
                -DSDL_STATIC=ON \
                -DSDL_SHARED=ON \
                -S ./ \
                -B ./build/x86_64
          cmake --build ./build/x86_64 --config Release

    - name: Build SDL_image for arm64-v8a
      run: |
          cd SDLImage
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_SYSTEM_NAME=Android \
                -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME \
                -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
                -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang \
                -DCMAKE_ANDROID_STL_TYPE=c++_shared \
                -DCMAKE_ANDROID_API=21 \
                -DSDL2_INCLUDE_DIR=./SDL2/include \
                -DSDL2_LIBRARY=./SDL2/build/arm64-v8a/libSDL2.so \
                -S ./ \
                -B ./build/arm64-v8a
          cmake --build ./build/arm64-v8a --config Release

    - name: Build SDL_image for x86_64
      run: |
          cd SDLImage
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_SYSTEM_NAME=Android \
                -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME \
                -DCMAKE_ANDROID_ARCH_ABI=x86_64 \
                -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang \
                -DCMAKE_ANDROID_STL_TYPE=c++_shared \
                -DCMAKE_ANDROID_API=21 \
                -DSDL2_INCLUDE_DIR=./SDL2/include \
                -DSDL2_LIBRARY=./SDL2/build/x86_64/libSDL2.so \
                -S ./ \
                -B ./build/x86_64
          cmake --build ./build/x86_64 --config Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.4
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-artifacts 
        path: |
          SDLImage/build/arm64-v8a/*.so
          SDLImage/build/x86_64/*.so
        if-no-files-found: ignore # 'warn' or 'ignore' or 'error'
